### ISSUE TITLE
Running driver gives IllegalAccessError

### ISSUE THREAD

**Issue by mxwli** [ldbc/ldbc_snb_interactive_v1_driver#232]
I am trying to run the reference neo4j benchmark found in the v1 reference implementations. During the tests in `mvn clean package`, I get the following error message:

```
[ERROR]   DisruptorSbeMetricsServiceTest.shouldNotAcceptOperationResultsAfterShutdown:36 » IllegalAccess class uk.co.real_logic.sbe.codec.java.DirectBuffer (in unnamed module @0x6fa4fbe3) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x6fa4fbe3
[ERROR]   DisruptorSbeMetricsServiceTest.shouldReturnCorrectMeasurements:66 » IllegalAccess class uk.co.real_logic.sbe.codec.java.DirectBuffer (in unnamed module @0x6fa4fbe3) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x6fa4fbe3
[ERROR]   SbeEventTest.shouldReadWrites:14 » IllegalAccess class uk.co.real_logic.sbe.codec.java.DirectBuffer (in unnamed module @0x6fa4fbe3) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x6fa4fbe3
[ERROR]   InteractiveWorkloadTest>WorkloadTest.shouldLoadFromConfigFile:347 » IllegalAccess class uk.co.real_logic.sbe.codec.java.DirectBuffer (in unnamed module @0x6fa4fbe3) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x6fa4fbe3
[ERROR]   InteractiveWorkloadTest>WorkloadTest.shouldRunWorkload:443 » IllegalAccess class uk.co.real_logic.sbe.codec.java.DirectBuffer (in unnamed module @0x6fa4fbe3) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x6fa4fbe3
```

So instead, I tried directly using the drivers found in the [snb-mvn repository](https://github.com/ldbc/snb-mvn), and I receive this error message:
```
Exception in thread "main" java.lang.IllegalAccessError: class uk.co.real_logic.sbe.codec.java.DirectBuffer (in unnamed module @0x6fa4fbe3) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x6fa4fbe3
        at uk.co.real_logic.sbe.codec.java.DirectBuffer.wrap(DirectBuffer.java:104)
        at uk.co.real_logic.sbe.codec.java.DirectBuffer.<init>(DirectBuffer.java:57)
        at org.ldbcouncil.snb.driver.runtime.metrics.DisruptorSbeMetricsEvent$MetricsCollectionEventFactory.newInstance(DisruptorSbeMetricsEvent.java:48)
        at org.ldbcouncil.snb.driver.runtime.metrics.DisruptorSbeMetricsEvent$MetricsCollectionEventFactory.newInstance(DisruptorSbeMetricsEvent.java:41)
        at com.lmax.disruptor.RingBufferFields.fill(RingBuffer.java:84)
        at com.lmax.disruptor.RingBufferFields.<init>(RingBuffer.java:77)
        at com.lmax.disruptor.RingBuffer.<init>(RingBuffer.java:116)
        at com.lmax.disruptor.RingBuffer.createMultiProducer(RingBuffer.java:134)
        at com.lmax.disruptor.RingBuffer.create(RingBuffer.java:200)
        at com.lmax.disruptor.dsl.Disruptor.<init>(Disruptor.java:98)
        at org.ldbcouncil.snb.driver.runtime.metrics.DisruptorSbeMetricsService.<init>(DisruptorSbeMetricsService.java:65)
        at org.ldbcouncil.snb.driver.client.ExecuteWorkloadMode.doInit(ExecuteWorkloadMode.java:263)
        at org.ldbcouncil.snb.driver.client.ExecuteWorkloadMode.startExecutionAndAwaitCompletion(ExecuteWorkloadMode.java:105)
        at org.ldbcouncil.snb.driver.Client.main(Client.java:65)
```

Here is my environment:
```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 18.0.2-ea, vendor: Private Build, runtime: /usr/lib/jvm/java-18-openjdk-amd64
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "6.5.0-15-generic", arch: "amd64", family: "unix"
```
I'm inclined to believe it's a problem with my version of Java, but I can't find any specifications on which version I should be using.

What can I do to resolve this issue? Thanks.

**Comment by mxwli** [comment]
Update: I tried Java-11 and it worked.
